# Generated by Django 4.2.7 on 2026-06-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='business_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='business_stage',
            field=models.CharField(blank=True, choices=[('idea', 'Idea'), ('startup', 'Startup'), ('growth', 'Growth'), ('established', 'Established')], max_length=20),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Comma-separated list of certifications'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='performance_score',
            field=models.FloatField(default=0),
        ),
    ]
