# Generated by Django 4.2.7 on 2026-06-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('excerpt', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('author', models.CharField(default='Thale-Quants Team', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('result', models.CharField(max_length=500)),
                ('roi', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='case_studies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_escalated', models.BooleanField(default=False)),
                ('escalated_to_email', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('enterprise', 'Enterprise Solutions'), ('entrepreneur', 'Entrepreneur Program'), ('both', 'Both')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('revenue_growth', 'Revenue Growth'), ('jobs_created', 'Jobs Created'), ('supplier_score', 'Supplier Score'), ('digital_adoption', 'Digital Adoption'), ('esd_impact', 'ESD Impact')], max_length=50)),
                ('display_value', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='📊', max_length=10)),
                ('progress_percentage', models.FloatField(default=0)),
                ('target_value', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('esd', 'ESD Report'), ('supplier', 'Supplier Report'), ('financial', 'Financial Report'), ('impact', 'Impact Report')], max_length=50)),
                ('generated_for', models.CharField(max_length=255)),
                ('generated_by', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('template', 'Template'), ('guide', 'Guide'), ('workbook', 'Workbook'), ('spreadsheet', 'Spreadsheet')], max_length=20)),
                ('file_format', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='resources/')),
                ('downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('enterprise_esd', 'Enterprise ESD'), ('enterprise_scouting', 'Enterprise Scouting'), ('enterprise_reporting', 'Enterprise Reporting'), ('entrepreneur_incubation', 'Entrepreneur Incubation'), ('entrepreneur_mentorship', 'Entrepreneur Mentorship'), ('entrepreneur_masterclass', 'Entrepreneur Masterclass')], max_length=50)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=500)),
                ('icon', models.CharField(default='📊', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('industry_sector', models.CharField(max_length=255)),
                ('financial_health_score', models.FloatField(default=0)),
                ('operational_excellence_score', models.FloatField(default=0)),
                ('digital_readiness_score', models.FloatField(default=0)),
                ('compliance_score', models.FloatField(default=0)),
                ('growth_potential_score', models.FloatField(default=0)),
                ('predicted_revenue_growth', models.FloatField(default=0)),
                ('predicted_job_creation', models.IntegerField(default=0)),
                ('risk_level', models.IntegerField(default=2)),
                ('ai_confidence_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('performance_category', models.CharField(blank=True, max_length=50)),
                ('last_assessed', models.DateTimeField(blank=True, null=True)),
                ('next_review_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='team/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_company', models.CharField(max_length=255)),
                ('client_role', models.CharField(max_length=255)),
                ('testimonial', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('insight_type', models.CharField(choices=[('risk', 'Risk Alert'), ('growth', 'Growth Opportunity'), ('compliance', 'Compliance Issue'), ('performance', 'Performance Insight')], max_length=50)),
                ('description', models.TextField()),
                ('confidence_level', models.FloatField(default=50)),
                ('is_actionable', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('related_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.supplier')),
            ],
        ),
    ]
